/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

/**
 *
 * @author Ryzen 5
 */
public class ConsultarPlacas extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarPlacas
     */
    public ConsultarPlacas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        headerImgLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        tituloLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        personaTable = new javax.swing.JTable();
        curpTxtField = new javax.swing.JTextField();
        nombreTxtField = new javax.swing.JTextField();
        fechaNacimientoTxtField = new javax.swing.JTextField();
        curpLabel = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        fechaNacimientoLabel = new javax.swing.JLabel();
        buscarPorLabel = new javax.swing.JLabel();
        buscarBtn = new javax.swing.JButton();
        consultarLabel = new javax.swing.JButton();
        volverLabel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 900));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 900));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(227, 227, 217));
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 130));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 130));

        headerImgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/marcoPantallaPrincipal.png"))); // NOI18N
        headerImgLabel.setText("a");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(headerImgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(headerImgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(227, 227, 217));
        jPanel2.setAlignmentX(0.0F);
        jPanel2.setAlignmentY(0.0F);
        jPanel2.setMinimumSize(new java.awt.Dimension(800, 770));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 770));

        tituloLabel.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        tituloLabel.setText("Seleccione a la persona a la cual se quiere consultar el historial de placas");

        personaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Jorge Elias", "JEIE46856161", "08/02/2024"},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "CURP", "Fecha de Nacimiento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        personaTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(personaTable);
        if (personaTable.getColumnModel().getColumnCount() > 0) {
            personaTable.getColumnModel().getColumn(0).setResizable(false);
            personaTable.getColumnModel().getColumn(1).setResizable(false);
            personaTable.getColumnModel().getColumn(2).setResizable(false);
        }

        curpTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curpTxtFieldActionPerformed(evt);
            }
        });

        curpLabel.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        curpLabel.setText("CURP");

        nombreLabel.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        nombreLabel.setText("Nombre");

        fechaNacimientoLabel.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        fechaNacimientoLabel.setText("Fecha de Nacimiento");

        buscarPorLabel.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        buscarPorLabel.setText("Buscar por: ");

        buscarBtn.setText("Buscar");

        consultarLabel.setText("Consultar");
        consultarLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarLabelActionPerformed(evt);
            }
        });

        volverLabel.setText("Volver");
        volverLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverLabelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tituloLabel)
                            .addComponent(buscarPorLabel)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(357, 357, 357)
                        .addComponent(consultarLabel))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(curpLabel)
                            .addComponent(curpTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(volverLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreLabel))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fechaNacimientoLabel)
                            .addComponent(fechaNacimientoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addComponent(buscarBtn))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(tituloLabel)
                .addGap(32, 32, 32)
                .addComponent(buscarPorLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLabel)
                    .addComponent(fechaNacimientoLabel)
                    .addComponent(curpLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(curpTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaNacimientoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarBtn))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(consultarLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(volverLabel)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void curpTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curpTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_curpTxtFieldActionPerformed

    private void volverLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverLabelActionPerformed
        this.dispose();
    }//GEN-LAST:event_volverLabelActionPerformed

    private void consultarLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarLabelActionPerformed
        this.setVisible(false);
        HistorialPlacas historialPlacas = new HistorialPlacas(this);
        historialPlacas.setVisible(true);
    }//GEN-LAST:event_consultarLabelActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarBtn;
    private javax.swing.JLabel buscarPorLabel;
    private javax.swing.JButton consultarLabel;
    private javax.swing.JLabel curpLabel;
    private javax.swing.JTextField curpTxtField;
    private javax.swing.JLabel fechaNacimientoLabel;
    private javax.swing.JTextField fechaNacimientoTxtField;
    private javax.swing.JLabel headerImgLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreTxtField;
    private javax.swing.JTable personaTable;
    private javax.swing.JLabel tituloLabel;
    private javax.swing.JButton volverLabel;
    // End of variables declaration//GEN-END:variables
}
