/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Presentacion;

import Entidades.Persona;
import Interfaces.IConexionBD;
import Negocio.ValidadoresLicencia;
import Persistencia.TramiteLicenciasDAO;
import Utilidades.ConstantesGUI;
import java.awt.event.ItemEvent;
import javax.persistence.EntityManager;
import javax.swing.JOptionPane;

/**
 *
 * @author JOSUE GOMEZ
 */
public class JDRenovarLicencia extends javax.swing.JDialog {

    IConexionBD conexion;
    Persona personaElegida;
    ConstantesGUI operaciones;
    private Integer vigenciaLicencia;
    private EntityManager entityManager;
    private Integer costoLicencia;
    private ValidadoresLicencia vLicencia;

    /**
     * Creates new form JDRenovarLicencia
     *
     * @param conexion
     * @param persona
     * @param parent
     * @param modal
     */
    public JDRenovarLicencia(IConexionBD conexion, Persona persona, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.conexion = conexion;
        this.personaElegida = persona;
        this.txtFieldCosto.setEditable(false);
        this.entityManager = conexion.crearConexion();
        this.vLicencia = new ValidadoresLicencia(conexion,this.entityManager);
        this.calcularCosto();

        this.settearNombrePersonaElegida();
    }

    /**
     *
     */
    public void settearNombrePersonaElegida() {
        nombreCliente2Label.setText(personaElegida.getNombres());
        nombreLabel.setText(personaElegida.getNombres());
    }

    /**
     * Método que calcula el costo de una licencia mediante la vigencia
     * seleccionada
     */
    private void calcularCosto() {
        String vigencia = (String) this.tipoVigenciaComboBox.getSelectedItem();
        if (vigencia.equalsIgnoreCase("1 AÑO")) {
            this.vigenciaLicencia = 1;
            if (personaElegida.isDiscapacitado()) {
                this.costoLicencia = 200;
                this.txtFieldCosto.setText("Costo: " + this.costoLicencia);
            } else {
                this.costoLicencia = 600;
                this.txtFieldCosto.setText("Costo: " + this.costoLicencia);
            }
        } else if (vigencia.equalsIgnoreCase("2 AÑOS")) {
            this.vigenciaLicencia = 2;
            if (personaElegida.isDiscapacitado()) {
                this.costoLicencia = 500;
                this.txtFieldCosto.setText("Costo: " + this.costoLicencia);
            } else {
                this.costoLicencia = 900;
                this.txtFieldCosto.setText("Costo: " + this.costoLicencia);
            }
        } else {
            this.vigenciaLicencia = 3;
            if (personaElegida.isDiscapacitado()) {
                this.costoLicencia = 700;
                this.txtFieldCosto.setText("Costo: " + this.costoLicencia);
            } else {
                this.costoLicencia = 1100;
                this.txtFieldCosto.setText("Costo: " + this.costoLicencia);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        headerImgLabel = new javax.swing.JLabel();
        tituloLabel = new javax.swing.JLabel();
        precioLabel = new javax.swing.JLabel();
        tipoVigenciaLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        volverBtn = new javax.swing.JButton();
        aceptarBtn = new javax.swing.JButton();
        tipoVigenciaComboBox = new javax.swing.JComboBox<>();
        nombreClienteLabel = new javax.swing.JLabel();
        clienteImgLabel = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        nombreCliente2Label = new javax.swing.JLabel();
        txtFieldCosto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(227, 227, 217));

        headerImgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/marcoPantallaPrincipal.png"))); // NOI18N

        tituloLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tituloLabel.setText("Requisitos de licencia");

        precioLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        precioLabel.setText("Precio:");

        tipoVigenciaLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tipoVigenciaLabel.setText("Tipo de vigencia:");

        volverBtn.setText("Volver");
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });

        aceptarBtn.setText("Aceptar");
        aceptarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarBtnActionPerformed(evt);
            }
        });

        tipoVigenciaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 AÑO", "2 AÑOS", "3 AÑOS" }));
        tipoVigenciaComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tipoVigenciaComboBoxItemStateChanged(evt);
            }
        });

        nombreClienteLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nombreClienteLabel.setText("Nombre del cliente:");

        clienteImgLabel.setBackground(new java.awt.Color(204, 0, 51));
        clienteImgLabel.setForeground(new java.awt.Color(204, 255, 0));
        clienteImgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/R (1).png"))); // NOI18N
        clienteImgLabel.setText("jLabel3");

        nombreLabel.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        nombreLabel.setText("Jorge Elias");

        nombreCliente2Label.setText("jLabel1");

        txtFieldCosto.setText("jTextField1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(volverBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(aceptarBtn)
                .addGap(48, 48, 48))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(tituloLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(headerImgLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nombreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(precioLabel)
                            .addComponent(tipoVigenciaLabel)
                            .addComponent(nombreClienteLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFieldCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tipoVigenciaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nombreCliente2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(clienteImgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(92, 92, 92))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(headerImgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tituloLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreClienteLabel)
                            .addComponent(nombreCliente2Label))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tipoVigenciaLabel)
                            .addComponent(tipoVigenciaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(clienteImgLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precioLabel)
                    .addComponent(txtFieldCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volverBtn)
                    .addComponent(aceptarBtn))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        dispose();

    }//GEN-LAST:event_volverBtnActionPerformed

    private void aceptarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarBtnActionPerformed
vLicencia.crearLicencia(personaElegida, vigenciaLicencia, costoLicencia);
        dispose();
    }//GEN-LAST:event_aceptarBtnActionPerformed

    private void tipoVigenciaComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tipoVigenciaComboBoxItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            calcularCosto();
        }
    }//GEN-LAST:event_tipoVigenciaComboBoxItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarBtn;
    private javax.swing.JLabel clienteImgLabel;
    private javax.swing.JLabel headerImgLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nombreCliente2Label;
    private javax.swing.JLabel nombreClienteLabel;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JLabel precioLabel;
    private javax.swing.JComboBox<String> tipoVigenciaComboBox;
    private javax.swing.JLabel tipoVigenciaLabel;
    private javax.swing.JLabel tituloLabel;
    private javax.swing.JTextField txtFieldCosto;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables
}
